services:
  plex:
    restart: always
    container_name: plex
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    environment:
      - TZ=America/Detroit
      - 'ADVERTISE_IP=https://[REPLACE WITH FQDN or IP]'
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
      - HOME=/config
      - GUID=1000
      - PUID=1000
      - VERSION=docker
      # First Time Setup: 
      # Go to – https://www.plex.tv/claim/
      # launch with claim code below
      #- PLEX_CLAIM=claim-XXXXXXXXXXXXXX
    volumes:
      - ./config:/config
      - plexmedia:/data
      - ./transcode:/transcode
    image: 'plexinc/pms-docker:latest'
    devices:
      - /dev/dri:/dev/dri
      
volumes:
  plexmedia:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.1.10
      device: :/volume1/PlexMedia