services:
  plex:
    restart: always
    container_name: plex
    ports:
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    environment:
      - TZ=America/Detroit
      - 'ADVERTISE_IP=http://[REPLACE WITH FQDN or IP]:32400'
      - CHANGE_CONFIG_DIR_OWNERSHIP=true
      - HOME=/config
      - GUID=1000
      - PUID=1000
      - VERSION=docker
      # First Time Setup: 
      # Go to – https://www.plex.tv/claim/
      # launch with claim code below
      #- PLEX_CLAIM=claim-XXXXXXXXXXXXXX
    volumes:
      - ./config:/config
      - mediaVol:/data
      - ./transcode:/transcode
    image: 'plexinc/pms-docker:latest'
    devices:
      - /dev/dri:/dev/dri
      
volumes:
  # Plex Media on NFS share
  #mediaVol:
  #  driver: local
  #  driver_opts:
  #    type: nfs
  #    o: addr=192.168.1.xxx
  #    device: :/nfs/PlexMedia

  # Plex Media in host path
  mediaVol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path_to_media_folder