services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
      - 8100:8100
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "8G"
      MOTD: "A Vanilla-ish Minecraft Server"
      USE_AIKAR_FLAGS: "true"
      TZ: "America/Detroit"
      SIMULATION_DISTANCE: "15"
      VIEW_DISTANCE: "25"
      OPS: |-
        notsle
      VANILLATWEAKS_SHARECODE: "jVtasb"
      PLUGINS: |-
        https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.5/bluemap-5.5-paper.jar
    volumes:
      - "./data:/data"
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=XXX
